In [6]:
pip install numpy


     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     ------ --------------------------------- 10.2/61.0 kB ? eta -:--:--
     ------------------------------- ------ 51.2/61.0 kB 525.1 kB/s eta 0:00:01
     -------------------------------------- 61.0/61.0 kB 540.4 kB/s eta 0:00:00
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB 1.3 MB/s eta 0:00:13
   ---------------------------------------- 0.1/15.8 MB 653.6 kB/s eta 0:00:25
   ---------------------------------------- 0.1/15.8 MB 726.2 kB/s eta 0:00:22
   ---------------------------------------- 0.2/15.8 MB 766.6 kB/s eta 0:00:21
    --------------------------------------- 0.2/15.8 MB 831.5 kB/s eta 0:00:19
    --------------------------------------- 0.2/15.8 MB 860.2 kB/s eta 0:00:19
    --------------------------------------- 0.3/15.8 MB 886.2 kB/s eta 0:00:18
    --------------------------------------- 0.3/15.8 MB 855.7 kB/s eta 0:0

ERROR: Could not install packages due to an OSError: [WinError 2] The system cannot find the file specified: 'C:\\Python310\\Scripts\\f2py.exe' -> 'C:\\Python310\\Scripts\\f2py.exe.deleteme'


[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [10]:
import numpy as np


In [11]:
random_int = np.random.randint(1,50,10)
random_int

array([ 3, 19, 43, 40, 20, 36,  5, 46, 29, 27])

In [12]:
np.mean(random_int)

26.8

In [14]:
a = np.random.randint(1,50,size=(3,3))
b = np.random.randint(1,50,size=(3,3))
a


array([[30, 37, 44],
       [48, 33, 30],
       [22, 37, 31]])

In [15]:
b

array([[39, 35, 11],
       [24, 45, 23],
       [ 6, 31, 42]])

In [16]:
c=a+b
c

array([[69, 72, 55],
       [72, 78, 53],
       [28, 68, 73]])

In [17]:
np.mean(c)

63.111111111111114

In [19]:
d = np.random.randint(1,100,20)
d

array([66, 29, 82, 42, 36, 88, 22, 83, 32, 39, 80, 73, 69,  7, 58, 26, 67,
       14, 51, 38])

In [20]:
condition = d > 50
filtered_d = d[condition]
filtered_d

array([66, 82, 88, 83, 80, 73, 69, 58, 67, 51])

In [21]:
arr=np.random.randint(1,100,10)
arr


array([77, 30, 63, 46, 63, 73, 63, 94, 84, 40])

In [25]:
np.random.shuffle(arr)
arr

array([63, 63, 40, 46, 63, 73, 77, 30, 84, 94])

In [29]:
x=np.random.randint(0,9)
x

5

In [30]:
arr[x]

73